api:
  build: ./api
  environment:
    - NODE_ENV=production
  ports:
    - "3000:3000"
  volumes:
    - "./api:/app"

tests:
  build: ./tests
  links:
    - api
  environment:
    - API_BASE_URI=http://api:3000
  volumes:
    - "./tests/specs:/app/specs"
