version: '2'

services:
  api:
    build: ./api
    environment:
      - NODE_ENV=production
    ports:
      - "3000"

  tests:
    build: ./tests
    depends_on:
      - api
    links:
      - api
    environment:
      - API_BASE_URI=http://api:3000
