version: '2'

services:
  api:
    extends:
      file: docker-compose.yml
      service: api
    command: [ watch ]
    ports:
      - "3000:3000"
    volumes:
      - "./api:/app"

  tests:
    extends:
      file: docker-compose.yml
      service: tests
    command: [ watch ]
    links:
      - api
    depends_on:
      - api
    volumes:
      - "./tests/specs:/app/specs"
